test_that("PROSPECT-D produces physically possible values", {
  lrt <- prospect()
  expect_true(all(lrt$reflectance >= 0))
  expect_true(all(lrt$reflectance <= 1))
  expect_true(all(lrt$transmittance >= 0))
  expect_true(all(lrt$transmittance <= 1))
  expect_true(all(lrt$transmittance <= 1))
  expect_true(length(lrt$reflectance)==length(lrt$transmittance))
  expect_true(length(lrt$reflectance)==2101)
})
